# Generated by Django 2.1.7 on 2019-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0003_aluno_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_turma',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
