# Generated by Django 2.1.7 on 2019-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0004_aluno_turma_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno_turma',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
