# Generated by Django 2.1.7 on 2019-04-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0005_auto_20190410_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_diciplina',
            name='faltas',
            field=models.IntegerField(null=True),
        ),
    ]
