# Generated by Django 2.1.7 on 2019-04-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0006_aluno_diciplina_faltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_diciplina',
            name='aprovados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
