# Generated by Django 2.1.7 on 2019-04-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0007_aluno_diciplina_aprovados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_turma',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='aluno_turma',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='turma_diciplina',
            name='cod_diciplina',
        ),
        migrations.RemoveField(
            model_name='turma_diciplina',
            name='cod_turma',
        ),
        migrations.RemoveField(
            model_name='aluno_diciplina',
            name='aprovados',
        ),
        migrations.DeleteModel(
            name='Aluno_Turma',
        ),
        migrations.DeleteModel(
            name='Turma_Diciplina',
        ),
    ]
