# Generated by Django 2.1.7 on 2019-06-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0010_auto_20190622_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_diciplina',
            name='n1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno_diciplina',
            name='n2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno_diciplina',
            name='n3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
