# Generated by Django 2.1.7 on 2019-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0012_auto_20190622_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_diciplina',
            name='faltas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aluno_diciplina',
            name='n1',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='aluno_diciplina',
            name='n2',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='aluno_diciplina',
            name='n3',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
