# Generated by Django 2.1.7 on 2019-06-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0016_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='diciplinas',
            field=models.ManyToManyField(to='lanc_notas.Diciplina'),
        ),
    ]
