# Generated by Django 2.1.7 on 2019-06-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0017_professor_diciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='diciplina',
            name='alunos',
            field=models.ManyToManyField(to='lanc_notas.Aluno'),
        ),
    ]
