# Generated by Django 2.1.7 on 2019-06-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0018_diciplina_alunos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diciplina',
            old_name='nome_diciplina',
            new_name='diciplina',
        ),
    ]
