# Generated by Django 2.1.7 on 2019-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0020_auto_20190629_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diciplina',
            name='alunos',
        ),
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
