# Generated by Django 2.1.7 on 2019-07-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0021_auto_20190702_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='status',
            new_name='semestre_fechado',
        ),
    ]
