# Generated by Django 2.1.7 on 2019-07-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0022_auto_20190702_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='semestre_fechado',
            new_name='aberto',
        ),
    ]
