# Generated by Django 2.1.7 on 2019-07-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanc_notas', '0024_auto_20190702_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_diciplina',
            name='semestre_aberto',
        ),
        migrations.AddField(
            model_name='diciplina',
            name='semestre_aberto',
            field=models.BooleanField(default=False),
        ),
    ]
